# primary/pg_hba.conf
local   all             all                                     trust
host    all             all             0.0.0.0/0               trust
host    replication     replicator      0.0.0.0/0               trust