services:
  db:
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    command: [
      "postgres",
      "-c", "config_file=/etc/postgresql/postgresql.conf"
    ]

volumes:
  pgdata: